### ISSUE TITLE
Lib项目缺少asp.net webapi client的nuget

### ISSUE THREAD

**Issue by liu4113231988** [hiwjcn/hiwjcn#37]
Lib项目缺少asp.net webapi client的nuget，还需要自己去nuget

**Comment by hiwjcn** [comment]
不明白你的意思，我记得lib里网络请求有个postjson依赖一个webapi的dll，其实也可以自己写application/json数据流。

**Comment by liu4113231988** [comment]
呢我下载编译失败的，手动获取nuget的asp.net webapi client才可以的，我就说下载看看学习学习搭建项目的
