### ISSUE TITLE
源代码编译时提示Invalid token '(' in class, struct, or interface member declaration)

### ISSUE THREAD

**Issue by tangjanghai** [hiwjcn/hiwjcn#40]
public static (List<T> list, int rowcount, int pagecount) ToPagedList<T>(this IOrderedQueryable<T> query, int page, int pagesize)
        {
            var count = query.QueryRowCountAndPageCount(pagesize);
            var list = query.QueryPage(page, pagesize).ToList();
            return (list, count.item_count, count.page_count);
        }
这个函数在编译时报错，这个使用的是什么语法呀，请指教。
编译时已将net framework版本改成了4.6

**Comment by hafei** [comment]
Tuples，new feature  in C# 7.0
https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/

**Comment by hiwjcn** [comment]
@tangjanghai 升级到vs2017，再安装system.valuetuple就好了
